/*
  Initial schema for toptanci-projesi
*/

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Companies')
BEGIN
  CREATE TABLE Companies (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Companies PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    CompanyName NVARCHAR(200) NOT NULL,
    TaxNumber NVARCHAR(50) NULL,
    TaxOffice NVARCHAR(150) NULL,
    Email NVARCHAR(255) NULL,
    Phone NVARCHAR(50) NULL,
    City NVARCHAR(100) NULL,
    District NVARCHAR(100) NULL,
    Address NVARCHAR(500) NULL,
    Status NVARCHAR(30) NOT NULL CONSTRAINT DF_Companies_Status DEFAULT 'PENDING',
    IsActive BIT NOT NULL CONSTRAINT DF_Companies_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Companies_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_Companies_UpdatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT CK_Companies_Status CHECK (Status IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED'))
  );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Users')
BEGIN
  CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Users PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    CompanyId UNIQUEIDENTIFIER NULL,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    PasswordHash NVARCHAR(255) NOT NULL,
    Phone NVARCHAR(50) NULL,
    Role NVARCHAR(30) NOT NULL,
    IsActive BIT NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Users_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_Users_UpdatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UQ_Users_Email UNIQUE (Email),
    CONSTRAINT CK_Users_Role CHECK (Role IN ('ADMIN', 'COMPANY_USER')),
    CONSTRAINT FK_Users_Companies FOREIGN KEY (CompanyId) REFERENCES Companies(Id)
  );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Categories')
BEGIN
  CREATE TABLE Categories (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Categories PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Name NVARCHAR(150) NOT NULL,
    Slug NVARCHAR(180) NOT NULL,
    Description NVARCHAR(1000) NULL,
    IsActive BIT NOT NULL CONSTRAINT DF_Categories_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Categories_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_Categories_UpdatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UQ_Categories_Slug UNIQUE (Slug)
  );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Products')
BEGIN
  CREATE TABLE Products (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Products PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    CategoryId UNIQUEIDENTIFIER NULL,
    Name NVARCHAR(250) NOT NULL,
    Slug NVARCHAR(280) NOT NULL,
    SKU NVARCHAR(100) NULL,
    Barcode NVARCHAR(100) NULL,
    Description NVARCHAR(MAX) NULL,
    Unit NVARCHAR(50) NULL,
    Price DECIMAL(18, 2) NULL,
    StockQuantity DECIMAL(18, 3) NULL,
    IsActive BIT NOT NULL CONSTRAINT DF_Products_IsActive DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Products_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_Products_UpdatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UQ_Products_Slug UNIQUE (Slug),
    CONSTRAINT FK_Products_Categories FOREIGN KEY (CategoryId) REFERENCES Categories(Id)
  );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ProductImages')
BEGIN
  CREATE TABLE ProductImages (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ProductImages PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    ProductId UNIQUEIDENTIFIER NOT NULL,
    CloudinaryPublicId NVARCHAR(500) NOT NULL,
    SecureUrl NVARCHAR(1000) NOT NULL,
    Width INT NULL,
    Height INT NULL,
    Format NVARCHAR(20) NULL,
    SortOrder INT NOT NULL CONSTRAINT DF_ProductImages_SortOrder DEFAULT 0,
    IsPrimary BIT NOT NULL CONSTRAINT DF_ProductImages_IsPrimary DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_ProductImages_CreatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ProductImages_Products FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE CASCADE
  );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Carts')
BEGIN
  CREATE TABLE Carts (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Carts PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    CompanyId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Carts_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_Carts_UpdatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Carts_Companies FOREIGN KEY (CompanyId) REFERENCES Companies(Id),
    CONSTRAINT FK_Carts_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT UQ_Carts_Company_User UNIQUE (CompanyId, UserId)
  );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CartItems')
BEGIN
  CREATE TABLE CartItems (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CartItems PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    CartId UNIQUEIDENTIFIER NOT NULL,
    ProductId UNIQUEIDENTIFIER NOT NULL,
    Quantity DECIMAL(18, 3) NOT NULL,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_CartItems_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_CartItems_UpdatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_CartItems_Carts FOREIGN KEY (CartId) REFERENCES Carts(Id) ON DELETE CASCADE,
    CONSTRAINT FK_CartItems_Products FOREIGN KEY (ProductId) REFERENCES Products(Id),
    CONSTRAINT UQ_CartItems_Cart_Product UNIQUE (CartId, ProductId),
    CONSTRAINT CK_CartItems_Quantity CHECK (Quantity > 0)
  );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Orders')
BEGIN
  CREATE TABLE Orders (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Orders PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    OrderNumber NVARCHAR(50) NOT NULL,
    CompanyId UNIQUEIDENTIFIER NOT NULL,
    CreatedByUserId UNIQUEIDENTIFIER NOT NULL,
    Status NVARCHAR(30) NOT NULL CONSTRAINT DF_Orders_Status DEFAULT 'PENDING_APPROVAL',
    Subtotal DECIMAL(18, 2) NOT NULL,
    GrandTotal DECIMAL(18, 2) NOT NULL,
    CustomerNote NVARCHAR(1000) NULL,
    AdminNote NVARCHAR(1000) NULL,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Orders_CreatedAt DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_Orders_UpdatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UQ_Orders_OrderNumber UNIQUE (OrderNumber),
    CONSTRAINT CK_Orders_Status CHECK (Status IN (
      'PENDING_APPROVAL', 'APPROVED', 'PREPARING', 'SHIPPED', 'DELIVERED', 'REJECTED', 'CANCELLED'
    )),
    CONSTRAINT FK_Orders_Companies FOREIGN KEY (CompanyId) REFERENCES Companies(Id),
    CONSTRAINT FK_Orders_Users FOREIGN KEY (CreatedByUserId) REFERENCES Users(Id)
  );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'OrderItems')
BEGIN
  CREATE TABLE OrderItems (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_OrderItems PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    OrderId UNIQUEIDENTIFIER NOT NULL,
    ProductId UNIQUEIDENTIFIER NULL,
    ProductNameSnapshot NVARCHAR(250) NOT NULL,
    UnitSnapshot NVARCHAR(50) NULL,
    UnitPrice DECIMAL(18, 2) NOT NULL,
    Quantity DECIMAL(18, 3) NOT NULL,
    LineTotal DECIMAL(18, 2) NOT NULL,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_OrderItems_CreatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_OrderItems_Orders FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE,
    CONSTRAINT FK_OrderItems_Products FOREIGN KEY (ProductId) REFERENCES Products(Id)
  );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'OrderStatusHistory')
BEGIN
  CREATE TABLE OrderStatusHistory (
    Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_OrderStatusHistory PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    OrderId UNIQUEIDENTIFIER NOT NULL,
    OldStatus NVARCHAR(30) NULL,
    NewStatus NVARCHAR(30) NOT NULL,
    ChangedByUserId UNIQUEIDENTIFIER NULL,
    Note NVARCHAR(1000) NULL,
    CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_OrderStatusHistory_CreatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_OrderStatusHistory_Orders FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE,
    CONSTRAINT FK_OrderStatusHistory_Users FOREIGN KEY (ChangedByUserId) REFERENCES Users(Id)
  );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = '__Migrations')
BEGIN
  CREATE TABLE __Migrations (
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Migrations PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    AppliedAt DATETIME2 NOT NULL CONSTRAINT DF_Migrations_AppliedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UQ_Migrations_Name UNIQUE (Name)
  );
END
GO
